# Generated by Django 3.0.4 on 2020-05-24 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myblog',
            name='url',
        ),
        migrations.AddField(
            model_name='myblog',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='myblog',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='myblog',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
